services:
  Elbformat\SymfonyBehatBundle\Application\ApplicationFactory:
    arguments:
      $kernel: '@kernel'
  Elbformat\SymfonyBehatBundle\Browser\StateFactory: ~
  Elbformat\SymfonyBehatBundle\Helper\ArrayDeepCompare: ~
  Elbformat\SymfonyBehatBundle\Helper\StringCompare: ~